### ISSUE TITLE
Create authorization request to Google

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#2]
The first step in the OAuth protocol is to create the authorization request to Google (see https://developers.google.com/identity/protocols/OAuth2WebServer)

This is an https to an endpoint build based on the `client_id` of the Google application. The two other required data are `redirect_uri` where the Google code is sent to on your server (the code will be exchange with the user's token on the next step) and `scope` which define what the application can access on behalf of the user.

- [x] Create a test application on Google to generate a `client_id`
- [x] Generate the Google linked to be used to login with Google (post request)

**Comment by SimonLab** [comment]
Simple scope we can use for the application:
https://developers.google.com/identity/protocols/googlescopes#google_sign-in

**Comment by SimonLab** [comment]
Having an issue with the redirect url. I'm not sure the settings are saved properly on the google console :thinking: 
![image](https://user-images.githubusercontent.com/6057298/69153323-ec7abd00-0ad5-11ea-8bce-5943372d8c2c.png)

**Comment by nelsonic** [comment]
@SimonLab want to pair on it after lunch?

**Comment by SimonLab** [comment]
I've manage to find what's the issue on this:
![image](https://user-images.githubusercontent.com/6057298/69153804-c7d31500-0ad6-11ea-97fa-d8afa7973084.png)

https://stackoverflow.com/questions/24363041/redirect-uri-in-google-cloud-console-doesnt-save

I'll just check that this work and I'll clean the PR for this url function

**Comment by SimonLab** [comment]
working now:
![image](https://user-images.githubusercontent.com/6057298/69154091-46c84d80-0ad7-11ea-8dd3-ca3c865b9213.png)

and it redirects to the application with the code (I need now to create the endpoint on the Phoenix app)
![image](https://user-images.githubusercontent.com/6057298/69154153-63648580-0ad7-11ea-931d-a2628b9643ba.png)

**Comment by SimonLab** [comment]
done with #3
