### ISSUE TITLE
protocol String.Chars not implemented for %{"email_verified" => "false"} of type Map

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#20]
Part of documenting #10 this package is attempting to create an app that uses the package from scratch. I am creating the _absolute_ minimum steps example in: https://github.com/dwyl/auth-demo

When I attempt to access the `"email_verified"` property of the `profile` (_returned by Google_)
in a template e.g:

```html
<section class="phx-hero">
  <%= @profile.email_verified != "true" do %>

    <h1>Welcome to Awesome App!</h1>
    <p>To get started, login to your Google Account: <p>
    <a href="<%= @oauth_google_url %>">
      <img src="https://i.imgur.com/Kagbzkq.png" alt="Sign in with Google" />
    </a>
  <% else %>
    <h1> Welcome <%= @profile["given_name"] %> </h1>
  <% end %>
</section>
```

I see the following error:

![image](https://user-images.githubusercontent.com/194400/70195114-a429e480-16fc-11ea-84a7-06ba040582c3.png)

```
protocol String.Chars not implemented for %{"email_verified" => "false"} of type Map
```

This is _very_ unfriendly to end users (_the beginners who are attempting to consume the package_).
This is partly `Elixir` being unfriendly and partly our fault for not _making_ the `profile` map easier to use.

I feel we could improve this by transforming the keys of the `profile` map from strings to atoms.
https://stackoverflow.com/questions/31990134/convert-map-keys-from-strings-to-atoms-in-elixir

Specifically in the `parse_body_response` currently:
https://github.com/dwyl/elixir-auth-google/blob/687fba552db8b5de2d353d42f77e2f04d9d428f9/lib/elixir_auth_google.ex#L38-L45

Could be:
```elixir
  def parse_body_response({:ok, response}) do
    body = Map.get(response, :body)
    if body == nil do
      {:error, :no_body}
    else # make keys of map atoms for easier access in templates
      {:ok, str_key_map} = Poison.decode(body)
      atom_key_map = for {key, val} <- str_key_map, into: %{},
        do: {String.to_atom(key), val}
      {:ok, atom_key_map}
    end # https://stackoverflow.com/questions/31990134
  end
```

So that instead of returning a Map where they keys are **strings**:
```elixir
%{
  "email" => "nelson@gmail.com",
  "email_verified" => true,
  "family_name" => "Correia",
  "given_name" => "Nelson",
  "locale" => "en",
  "name" => "Nelson Correia",
  "picture" => "https://lh3.googleusercontent.com/a-/AAuE7mApnYb260YC1JY7",
  "sub" => "940732358705212133793"
}
```
The `parse_body_response` would return a Map where the keys are ***atoms***:

```elixir 
%{
  email: "nelson@gmail.com",
  email_verified: true,
  family_name: "Correia",
  given_name: "Nelson",
  locale: "en",
  name: "Nelson Correia",
  picture: "https://lh3.googleusercontent.com/a-/AAuE7mApnYb260YC1JY7",
  sub: "940732358705212133793"
}
```

**Comment by nelsonic** [comment]
@SimonLab thanks for sense checking this suggestion and merging my PR #22 👍

**Comment by jasmo2** [comment]
It still have the error even with the atoms

The way are been call is like this:
`ElixirAuthGoogle.get_user_profile(token)`

`protocol String.Chars not implemented for %{email: "em@mail.com", email_verified: true, family_name: "OKAY", given_name: "OKAY", locale: "en-GB", name: "OK OK"} of type Map`

**Comment by jasmo2** [comment]
`ElixirAuthGoogle.get_user_profile(token)`

Still getting the issue:
`protocol String.Chars not implemented for %{email: "...", ...} of type Map`

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/elixir-auth-google/issues/28 (_issue for discussing this_)
