### ISSUE TITLE
BUG | protocol String.Chars not implemented for %{email: "em@mail.com", email_verified: true, family_name: "OKAY", given_name: "OKAY", locale: "en-GB", name: "OK OK"} of type Map

### ISSUE THREAD

**Issue by jasmo2** [dwyl/elixir-auth-google#28]
It still have the error even with the atoms

The way are been call is like this:
`ElixirAuthGoogle.get_user_profile(token)`

`protocol String.Chars not implemented for %{email: "em@mail.com", email_verified: true, family_name: "OKAY", given_name: "OKAY", locale: "en-GB", name: "OK OK"} of type Map`

**Comment by jasmo2** [comment]
It is weird because when I pass the token directly in console`iex -s mix` 
`ElixirAuthGoogle.get_user_profile(token)`
It returns without any error.

**Comment by nelsonic** [comment]
@jasmo2 that *is* wired ... 🤔

**Comment by jasmo2** [comment]
Here I attach a preview of where the error is happening and where succeeding.
The same is happening on the phoenix app.

<img width="720" alt="Example_working_and_Error" src="https://user-images.githubusercontent.com/4839412/72209911-fd1a3480-3481-11ea-9863-864646fa88bc.png">

**Comment by nelsonic** [comment]
@jasmo2 what version of Elixir/Erlang/OTP are you running?

**Comment by jasmo2** [comment]
> Elixir 1.9.4 (compiled with Erlang/OTP 22)

**Comment by nelsonic** [comment]
@jasmo2 Thanks for confirming Elixir version. 👍 
Can you try running the demo app https://github.com/dwyl/elixir-auth-google-demo on your `localhost` (_or wherever you are trying to run your code..._)

**Comment by jasmo2** [comment]
It is working using the DEMO.
the issue is due to I want to use the library as just server side, to get the information. There the error is raise.

<img width="849" alt="Screen Shot 2020-01-12 at 1 21 49 PM" src="https://user-images.githubusercontent.com/4839412/72223602-a6266500-353e-11ea-948e-59cdf9527ce2.png">

**Comment by nelsonic** [comment]
@jasmo2 OK, cool. It's good to have a known (working) state as a starting point. ✅ 
Can you try to _modify_ the Demo app on your `localhost` to just invoke the function you want on line 10 of the [`google_auth_controller.ex`](https://github.com/dwyl/elixir-auth-google-demo/blob/d1a42e3855b63ba5719737cd4c533131b7add9ae/lib/app_web/controllers/google_auth_controller.ex#L9-L10)
That way we know if the invocation of `ElixirAuthGoogle.get_user_profile/1` is doing what you expect it to. 👍 
i.e. import the desired functionality into the Demo app and then when it's working, port it back to your "real" app. 💭

**Comment by nelsonic** [comment]
@jasmo2 any progress? 😊

**Comment by nelsonic** [comment]
@jasmo2 were you able to get it working? 💭

**Comment by nelsonic** [comment]
Closing as no follow up feedback from OP and we cannot replicate the issue. 
If still an issue, please re-open and give more info. Thanks.
