### ISSUE TITLE
Define redirect endpoint

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#31]
The callback endpoint is currently hardcoded with:
```elixir 
 def generate_redirect_uri(conn) do
    get_baseurl_from_conn(conn) <> "/auth/google/callback"
  end
```

I propose that we have an option to let the user define this callback url:

```elixir 
 def generate_redirect_uri(conn, callback_endpoint) when is_binary callback_endpoint do
    get_baseurl_from_conn(conn) <> callback_endpoint
  end
```

**Comment by nelsonic** [comment]
@SimonLab the point of having a _hard-coded_ callback endpoint is to have a ["sensible default"](https://en.wikipedia.org/wiki/Convention_over_configuration).

Having a callback of `/callback` as in `http://localhost:4000/callback` might feel like less to type in the short run, but it's a recipe for confusion the moment there is more than _one_ callback function in any app that is using this package. Having a namespaced URL `/auth/google/callback` makes it _very_ clear what the endpoint is for. 

I can see the appeal to make this configurable but I _don't_ understand _why_ the Phoenix App cannot simply use the existing callback URL? What is the _use-case_ for making the callback URL something different? 
_Our_ apps are _always_ going to use the namespaced route for consistency/clarity.

**Comment by SimonLab** [comment]
While adding the package to the Phoenix app, I've created the callback endpoint under the `api`` scope as I only have api endpoints at the moment on my router.ex:
```elixir
  scope "/api", AuthApiWeb do
    pipe_through :api
    get "/auth/google/callback", GoogleAuthController, :index
    get "/auth/github/callback", GithubAuthController, :index
    get "/auth/urls", AuthUrlController, :index
  end
```

I can remove the endpoint from the scope but it felt strange to seperate the endoints as I consider them to be apis:

```elixir
  scope "/", AppApiWeb do
    pipe_through :api
    get "/auth/google/callback", GoogleAuthController, :index
    get "/auth/github/callback", GithubAuthController, :index
  end

  scope "/api", AppApiWeb do
    pipe_through :api
    get "/auth/urls", AuthUrlController, :index
  end
```

I understand it adds a bit more complexity to the package, however we still have the default redirect with `generate_oauth_url/1`:

```elixir
  def generate_oauth_url(conn) do
    client_id = System.get_env("GOOGLE_CLIENT_ID")
    scope = System.get_env("GOOGLE_SCOPE") || "profile email"
    redirect_uri = generate_redirect_uri(conn)

    "#{@google_auth_url}&client_id=#{client_id}&scope=#{scope}&redirect_uri=#{redirect_uri}"
  end
```

and if user wants to specify another endpoint they can call `generate_oauth_url/2` with:
```elixir
  def generate_oauth_url(conn, callback_endpoint) do
    client_id = System.get_env("GOOGLE_CLIENT_ID")
    scope = System.get_env("GOOGLE_SCOPE") || "profile email"
    redirect_uri = generate_redirect_uri(conn, callback_endpoint)

    "#{@google_auth_url}&client_id=#{client_id}&scope=#{scope}&redirect_uri=#{redirect_uri}"
  end
```

However this feature is not a blocker for me.

**Comment by nelsonic** [comment]
@SimonLab do we _need_ to have _separate_ endpoint for API?

**Comment by SimonLab** [comment]
> do we need to have separate endpoint for API?
I'm not sure what you mean.
At the moment I only have defined api endpoints and I'm using the `pipe_through :api`.
I guess it's more a naming issue that I try to fix via the package instead of the application

**Comment by nelsonic** [comment]
Can we just use [content_negotiation](https://en.wikipedia.org/wiki/Content_negotiation) to switch between HTML and JSON handlers based on the content type of the request? i.e. use the _same_ route for both API and Browser (HTML) requests.

**Comment by SimonLab** [comment]
Yes we can use plug and `pipe_through :api` or `pipe_through :browser` to check the request type. Although I don't think google is restricting the request to a certain acceptance type for the redirect url.

My controller link to the redirect url doesn't returns any html (only json). I just wanted to have this endpoint matching the same naming as the other api endpoint (starting with `/api/...`)

I can see that it add more code than needed for now, so I'm closing this issue/PR
