### ISSUE TITLE
Export TestDouble Function in Hex Package

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#35]
At present we are not explicitly exporting the Mock version of HTTPoison in our Hex package.
Which means that the we need to have a Mock implementation in each "consumer" project.
See: https://github.com/dwyl/auth-mvp/blob/9836d31b501a731fcedfdd8a0d4fe026d105bda2/lib/mock/elixir_auth_google.ex#L1-L27

I propose that we take this a step further and actually check the `MIX_ENV` in the `elixir-auth-google` package and if `MIX_ENV=test` we return the Mock version of the functions. 
e.g: https://github.com/dwyl/elixir-auth-google/blob/master/lib/httpoison/in_memory.ex
This way the person _using_ the package never has to _think_ about creating their own mocks and simply copy-paste the sample tests to achieve 100% test coverage in their project. 

I don't know if this is an "anti pattern" or a "best practice" so I've opened a question to find out:
https://softwareengineering.stackexchange.com/questions/408267/is-it-a-best-practice-or-anti-pattern-to-export-mock-versions-of-functions-for-a
<img width="1423" alt="software-engineering-question" src="https://user-images.githubusercontent.com/194400/78243072-fe845780-74da-11ea-844d-5fe5c77f56e3.png">
> Asking questions is the _only_ way to learn. If you aren't asking questions you aren't learning. 

I think I _want_ to export the Mocks regardless of what other people say - because I don't want to have to _duplicate_ this code in the Auth project - but I'm _curious_ what the "best practice" is.

**Comment by SimonLab** [comment]
>I propose that we take this a step further and actually check the MIX_ENV in the elixir-auth-google package and if MIX_ENV=test we return the Mock version of the functions.
e.g: https://github.com/dwyl/elixir-auth-google/blob/master/lib/httpoison/in_memory.ex
This way the person using the package never has to think about creating their own mocks and simply copy-paste the sample tests to achieve 100% test coverage in their project.

I like this idea. Having an test example as documentation for the users should be enough for them to cover the authentication testing. At the moment I don't see any cases where the users would want to customise the return values of the mock but it could be added later on if necessary.

**Comment by nelsonic** [comment]
Got a reply on StackExchange:
![image](https://user-images.githubusercontent.com/194400/78271269-da893c00-7503-11ea-95a0-7c1eb11c7049.png)

The correct technical term is a "TestDouble". 
I'm going to make an attempt at this and will assign the PR when ready. 👍

**Comment by nelsonic** [comment]
Sadly, Module attribute based dependency injection did not work. 
So I had to go searching ... 
https://blog.carbonfive.com/2018/03/19/lightweight-dependency-injection-in-elixir-without-the-tears
Using a function to inject the dependency worked. 👍

**Comment by nelsonic** [comment]
PR: #36

**Comment by nelsonic** [comment]
It never ceases to amaze me how some people _down-vote_ questions ...
![image](https://user-images.githubusercontent.com/194400/78401756-5c0ac800-75f1-11ea-8821-b9c70fd44129.png)
Some people just don't have _anything_ better to do so they have crap on others. 🤦‍♂

**Comment by nelsonic** [comment]
Meanwhile, there are a couple of answers on my original SoftwareEngineering question. 
Exporting a **`TestDouble`** is very much a standard practice
and we have applied it to several of our projects now. 👍
