### ISSUE TITLE
Latest release breaks production release

### ISSUE THREAD

**Issue by PaulOstazeski** [dwyl/elixir-auth-google#37]
Hi. In production runtimes (at least using `MIX_ENV=prod mix release`), `Mix` is not available. This causes the following error in v1.1.1(https://github.com/dwyl/elixir-auth-google/releases/tag/v1.1.1).
I believe this came from #36.

```
** (exit) an exception was raised:                                                                                                                                                                                       ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
Mix.env() 
(elixir_auth_google) lib/elixir_auth_google.ex:11: ElixirAuthGoogle.inject_poison/0
(elixir_auth_google) lib/elixir_auth_google.ex:72: ElixirAuthGoogle.get_token/2
```

**Comment by nelsonic** [comment]
@PaulOstazeski Thanks for opening this issue. We are investigating this now. 🔍

**Comment by nelsonic** [comment]
@PaulOstazeski could you please give us a bit more detail about the target environment where you are running your app? We have a demo version of this app: https://github.com/dwyl/elixir-auth-google-demo
which is using the latest version of the package `{:elixir_auth_google, "~> 1.2.0"}`
And is working fine for us: https://elixir-auth-google-demo.herokuapp.com/

Works as expected:
![image](https://user-images.githubusercontent.com/194400/79796532-a4deb280-834d-11ea-84f5-b7fbc9877287.png)

When we attempt to run `MIX_ENV=prod mix release` on our `localhost` 
(Mac 10.15.4 with `Elixir 1.10.1` (compiled with Erlang/OTP 22))

We see the following output:

```
Generated phoenix app
==> app
Compiling 13 files (.ex)
Generated app app
* assembling app-1.2.0 on MIX_ENV=prod
* skipping runtime configuration (config/releases.exs not found)
* skipping elixir.bat for windows (bin/elixir.bat not found in the Elixir installation)
* skipping iex.bat for windows (bin/iex.bat not found in the Elixir installation)

Release created at _build/prod/rel/app!

    # To start your system
    _build/prod/rel/app/bin/app start

Once the release is running:

    # To connect to it remotely
    _build/prod/rel/app/bin/app remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/prod/rel/app/bin/app stop

To list all commands:

    _build/prod/rel/app/bin/app
```

Then when we run `_build/prod/rel/app/bin/app start` to star the app, it works as expected.
We aren't seeing any errors relating to `MIX_ENV` not being set.
If you can give us more detail (as much as possible) we can help debug.

Thanks.

**Comment by nelsonic** [comment]
@PaulOstazeski can you please try using `{:elixir_auth_google, "~> 1.2.0"}` thanks!

**Comment by PaulOstazeski** [comment]
Sure, I've got a bare-bones reproduction [here](https://github.com/PaulOstazeski/elixirauthgoogleissue37). This was extracted from the project where we saw the issue and is using the same build script. The actual app is hosted on render.com. The README in the repo I'm sharing contains the steps to trigger the error.

**Comment by PaulOstazeski** [comment]
I've kept researching, and I've found some seemingly similar issues elsewhere (or at least cases where folks found that the Mix module wasn't/isn't available in production).

- https://stackoverflow.com/questions/35888575/mix-env-0-equivalent-in-production-env
- https://elixirforum.com/t/mix-env-in-production-no-longer-produces-nil-but-crashes-mix-state-genserver/16165/7 (includes the comment "The general solution here is to not call Mix.env in runtime code")
- A pretty old heroku buildpack issue https://github.com/goshakkk/heroku-buildpack-elixir/issues/13

**Comment by nelsonic** [comment]
Yeah, that's _really_ annoying. I wouldn't have expected it to throw an `exception`... 😞 
@PaulOstazeski did you try adding `:mix` to your `extra_applications` list?
The same way that you added `:guardian` in `mix.exs`:
https://github.com/PaulOstazeski/elixirauthgoogleissue37/blob/75a76e3b55fa923731860f876808427cd3d06449/mix.exs#L23
As suggested in:  https://elixirforum.com/t/mix-env-in-production-no-longer-produces-nil-but-crashes-mix-state-genserver/16165/4
That appears to make it available in the release and thus it will return `Mix.env() >> :prod`

**Comment by PaulOstazeski** [comment]
Yes, that does work. Thanks.

**Comment by nelsonic** [comment]
@PaulOstazeski thanks for confirming that adding `:mix` to your `extra_applications` worked. 👍

**Comment by jtormey** [comment]
I just hit this issue as well, and can confirm the `:extra_applications` fix does work.

This seems like it's more of a workaround though, since it's not usually necessary to include mix in production releases. Instead, it's possible to store this information at compile time so that there's no opportunity for a runtime error:

```elixir
@compile_env Mix.env()

def inject_poison() do
  @compile_env == :test && ElixirAuthGoogle.HTTPoisonMock || HTTPoison
end
```

Happy to validate and open a PR if you'd like!

**Comment by nelsonic** [comment]
@jtormey if you have time, please open a PR adding this to the `README.md` 🙏

**Comment by nelsonic** [comment]
https://hex.pm/packages/elixir_auth_google/1.4.0 contains the update made by @jtormey with compile-time checking. :shipit:
