### ISSUE TITLE
How to makes sure required configuration value are set?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#4]
To create the Google url for login, the `client_id` of the Google application is required.
Once the user set the value in the application configuration we could use `Application.fetch_env!` function:

```elixir
  def login_url do
    client_id = Application.fetch_env!(:elixir_auth_google, :client_id)
    "Google url for the application with client id: #{client_id}"
  end
```

If the `client_id` is not properly set an error is returned.
![image](https://user-images.githubusercontent.com/6057298/69068746-36539c80-0a1d-11ea-88a9-43c27d7d7ca6.png)

However I think the error is only raised when the `login` function is called, not before.
It would be nicer to have the error raised when the application is starting not when it already runs.

**Comment by nelsonic** [comment]
@SimonLab good point. This can be achieved in the config.exs file whereby the “consuming” app will fail to load if the environment variable is unset/undefined. LMK (assign you me) if you get stuck. 👍🏻

**Comment by SimonLab** [comment]
Thanks @nelsonic 
Fetching the environment variable with `System.fetch_env!` in `config.exs` will indeed raise an error on start if the variable is not defined:

```elixir
config :elixir_auth_google,
  client_id: System.fetch_env!("GOOGLE_CLIENT_ID")
```

We just need to make sure the elixir version used is 1.9 as `System.fetch_env!` is only defined from then.

**Comment by nelsonic** [comment]
Indeed. thankfully we can enforce `Elixir v1.9` for our app(s) and inform future users of the package. 👍

**Comment by SimonLab** [comment]
On ubuntu I'm using [asdf](https://github.com/asdf-vm/asdf-elixir) to manage erlang and elixir versions.
To update my elixir to 1.9:
- `asdf update` to update asdf
- check the available elixir versions: https://bobs-list.kobrakai.de/
- `asdf install elixir 1.9` install new elixir version
- `asdf list` check the list of install versions
- `asdf global elixir 1.9` set the new installed version to be used by default

**Comment by nelsonic** [comment]
@SimonLab this is worth sharing on https://github.com/dwyl/learn-elixir#how

**Comment by nelsonic** [comment]
Superseded by #19 > #21
