### ISSUE TITLE
Create package as an OTP application?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#5]
At the moment the package is exposing a simple module containing the login_url function which can be called on the main application with `ElixirAuthGithub.login_url()`. This works fine but I'm wondering if there is a case to move the library to more encapsulated code by using OTP?

I'm thinking that an OTP application could provide a solution to the required configuration (see #4 ).

**Comment by nelsonic** [comment]
@SimonLab this is definitely worth exploring if it makes life easier for the developer *using* the package/module. 🤔
My gut instinct is that Elixir will already spawn a sub/child process for the HTTP request so in terms of memory/processing, it should be similar. 👍🏻

**Comment by nelsonic** [comment]
OTP App not a priority as this package is _really_ small and already runs in a separate process due to HTTP.
