### ISSUE TITLE
Compilation warning about Elixir version when using 1.13

### ISSUE THREAD

**Issue by sax** [dwyl/elixir-auth-google#57]
I noticed that the elixir version pinned in `mix.exs` is `~> 1.12.3`. The project seems compile fine on `1.13`, but issues a compiler warning.

**Comment by nelsonic** [comment]
@sax thanks for opening this issue to inform us. 👍

**Comment by nelsonic** [comment]
The action on this issue is to _either_ "relax" the requirements to avoid the warning.
Or explicitly update the version to `1.13` ... 💭 

Phoenix has: https://github.com/phoenixframework/phoenix/blob/de142f35e13e0e8661fa5d2eb7fa36f13b3d1158/mix.exs#L17
```elixir
@elixir_requirement "~> 1.9"

...

elixir: @elixir_requirement,
```

Wonder if this will do the trick. 🤔

**Comment by sax** [comment]
Last I checked there weren't any specific function calls that ~> 1.9 wouldn't support.

**Comment by nelsonic** [comment]
Closing as resolved. (We haven't seen this warning in practice on any of our apps using the package). 👍 
Please comment / re-open if you are still facing the issue. Thanks. 🙏
