### ISSUE TITLE
Define API for the package

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#6]
I'm thinking of having the following functions exposed by the package:

- `generate_oauth2_url`: return the Google url link where users can signin to the application (eg link for the "signin with Google" button), see #2 

When the user follow the link created by the function above, Google will send a request with the `code`. The package do not run a server on itself (yet?) so we'll need to delegate the creation of this callback endpoint to the user and write the documentation on how to do this. Ideally later on we could try to have the package do this step automatically 

- `get_token(code)`: This function can be used in the callback endpoint define by the user :arrow_up: . This will exchange the code send by google with the user's token which will allow the application to use the Google API.

- `get_profile(token)` : A function to get the basic information of the user.

**Comment by nelsonic** [comment]
@SimonLab sounds good. 👍 
We might not need the _digit_ in the first function `generate_oauth2_url` >> `generate_oauth_url`

**Comment by nelsonic** [comment]
API is well-defined. Thanks @SimonLab 👍

**Comment by nelsonic** [comment]
Documented: https://hexdocs.pm/elixir_auth_google/ElixirAuthGoogle.html
