### ISSUE TITLE
Welcome template missing

### ISSUE THREAD

**Issue by ndrean** [dwyl/elixir-auth-google#62]
Just like with the [Github login](https://github.com/dwyl/elixir-auth-github-demo), the [welcome view](https://github.com/dwyl/elixir-auth-github-demo#32-create-welcome-template-) section is missing.

**Comment by nelsonic** [comment]
Hi @ndrean 👋 
You are linking to the instructions in the ***demo*** app. 
We have an equivalent one for this package: 
https://github.com/dwyl/elixir-auth-google-demo#32-create-welcome-template-

**Comment by ndrean** [comment]
Ah, stupid indeed.

**Comment by nelsonic** [comment]
Not at all “stupid”. Apologies if I came across as harsh. We have lots of repos it’s an easy mistake. Hope you found the code+instructions useful. 👌🏻
