### ISSUE TITLE
Why did I have to create /views/googe_auth_new + templates/google_auth/welcome ?

### ISSUE THREAD

**Issue by ndrean** [dwyl/elixir-auth-google#63]
Tried to follow the guide but I had to create the files above. Did I do something wrong as you don't seem to need this.

**Comment by nelsonic** [comment]
@ndrean dis you follow the example: https://github.com/dwyl/elixir-auth-google-demo ? 🤞

**Comment by ndrean** [comment]
nope ....!      `|> put_view(LiveMapWeb.PageView)` ok!...

**Comment by nelsonic** [comment]
yes, the page is enough. 
as for the "old" style of writing embedded `Elixir` (`.eex`), 
you're right the (newer) curly brace syntax is simpler. 👍

**Comment by ndrean** [comment]
So I understand that if you don't use `put_view`, then you need to define  "/views/google_auth_view.ex" and "/templates/google_auth/welcome.html.heex". If you use `put_view`, then you can reference directly "/templates/page/welcome.html.heex".  Hence, you need to add the following:

4. Create a GoogleAuthController in your Project

```elixir
defmodule AppWeb.GoogleAuthController do
  use AppWeb, :controller
  def index(conn, %{"code" => code}) do
    {:ok, token} = ElixirAuthGoogle.get_token(code, conn)
    {:ok, profile} = ElixirAuthGoogle.get_user_profile(token.access_token)
    conn
     |> put_view(AppWeb.PageView)       <---------
     |> render(:welcome, profile: profile)
  end
end
```


6.1 Update the page/index.html.heex Template.        <----- "heex"
```elixir
<section class="phx-hero">
  <h1>Welcome to Awesome App!</h1>
  <p>To get started, login to your Google Account: <p>
  <a href={@oauth_google_url} >                                           <----------------------
    <img src="https://i.imgur.com/Kagbzkq.png" alt="Sign in with Google" />
  </a>
</section>
```
