### ISSUE TITLE
get_token api function

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#7]
Once the user agree to user the Google application, Google call our `redirect_uri` endpoint with the `code` passed as a parameter.

- [x] Create a function to request the user token from the code. We can use [HTTPoison](https://hexdocs.pm/httpoison/HTTPoison.html) from the application server to send a request to Google
see https://developers.google.com/identity/protocols/OAuth2WebServer#exchange-authorization-code

- [x] Update documentation to add `secret` config value to be able to get the token

**Comment by SimonLab** [comment]
Token received with HTTPoison:
![image](https://user-images.githubusercontent.com/6057298/69161210-b42dab80-0ae2-11ea-8757-c1c3b137429b.png)

**Comment by nelsonic** [comment]
@SimonLab looks good. thanks! 👍
