### ISSUE TITLE
Get user profile

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#9]
Google Plus API is now deprecated:
![image](https://user-images.githubusercontent.com/6057298/69221336-eb499e80-0b6e-11ea-8c7c-143d4f43c7cb.png)

After a while trying to find the documenatation I think the new endpoint to get the user profile is:
https://www.googleapis.com/oauth2/v3/userinfo?access_token=...

You don't need to enable other API on the Google console.
I've manage to get my user info directly via the browser, however I've got some error while parsing the response with `Poison` (I thin the request returned an error).
I'm going to check if the request needs specific headers to work

**Comment by SimonLab** [comment]
Getting the user information:
![image](https://user-images.githubusercontent.com/6057298/69226961-f6093100-0b78-11ea-969b-443a01159a05.png)

The mix dependency wasn't up to date!

**Comment by SimonLab** [comment]
The information available are defined by the scopes which can be 
`profile` returns `family_name, `given_name`, `name`, `picture`, `sub`
`email` returns `email`, `email_verified`, `picture`, `sub`
`openid` returns `picture`, `sub`

(I've tested the returns value manually by inspecting the returned values so maybe more information can be displayed?)

see https://developers.google.com/identity/protocols/googlescopes#google_sign-in
![image](https://user-images.githubusercontent.com/6057298/69728642-b31cff80-111c-11ea-9c96-5525e6e551b1.png)


You can combine scopes by adding space between them, for example if you want to get the profile information and the email information you can use the scope `profile email`.

The scope value is used to create the Google authentication url and will define which information will be accessible:

https://github.com/dwyl/elixir-auth-google/blob/2b1f9b09433fb7845dff00f593edd8fa29825f5f/lib/elixir_auth_google.ex#L10-L15

**Comment by nelsonic** [comment]
@SimonLab looks good. thanks. 👍
