### ISSUE TITLE
bug: Overriding scopes by enviromnent variables does not work properly on multiple scopes

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/elixir-auth-google#92]
I tried overriding the scopes by having an `.env` file and running `source .env` on my terminal and I had something like this:

`export GOOGLE_SCOPE=profile email calendar`

However, when I inspected the network request calls, I noticed that only `profile` was passed. 
When I reset my project and override by adding the configuration in `config/config.ex`, it worked as expected.

This means that the section in https://github.com/dwyl/elixir-auth-google#optional-scopes is wrong and needs some correction.
I didn't test it but maybe `export GOOGLE_SCOPE="profile email calendar"` works instead.

**Comment by nelsonic** [comment]
Indeed, the quotes are needed. 👍
