### ISSUE TITLE
Missing Typespec for Binary URL Input on generate_oauth_url/1 

### ISSUE THREAD

**Issue by wood-archer** [dwyl/elixir-auth-google#96]
I've noticed an issue in the following section of code: https://github.com/dwyl/elixir-auth-google/blob/main/lib/elixir_auth_google.ex#L81. It appears that a typespec hasn't been defined for scenarios where a binary URL is passed. This absence is causing Dialyzer contract violations for those who pass a URL as a binary string instead of utilizing `%Plug.Conn{}` or the `Endpoint.url/0` function.

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/elixir_auth_google/1.6.9 📦 
Please test. 🙏

**Comment by wood-archer** [comment]
Works like a charm! We thanks!

**Comment by nelsonic** [comment]
Thanks for confirming @wood-archer 👌  and thanks again for the swift and helpful contribution. 🚀
