### ISSUE TITLE
HTTPoison needs to be updated to be compatible with AuthPlug

### ISSUE THREAD

**Issue by wood-archer** [dwyl/elixir-auth-google#98]
#### Deps
```elixir
  {:auth_plug, "~> 1.5"},
  {:elixir_auth_google, "~> 1.6.8", override: true},
```

#### Output
```ssh
Because elixir_auth_google >= 1.6.6 depends on httpoison ~> 2.1.0 and auth_plug >= 1.4.1 depends on httpoison ~> 1.8.0, elixir_auth_google >= 1.6.6 is incompatible with auth_plug >= 1.4.1.
And because your app depends on auth_plug ~> 1.5, elixir_auth_google >= 1.6.6 is forbidden.
So, because your app depends on elixir_auth_google ~> 1.6.8, version solving failed.

**Comment by wood-archer** [comment]
Sorry, I should've say that the AuthPlug lib needs to update HTTPouison instead.

**Comment by nelsonic** [comment]
@wood-archer what is the context. 
Are you using `auth_plug` ...? 💭

**Comment by wood-archer** [comment]
After trying the elixir-with-google library, I wanted a quick way to authenticate without persisting data to a database so that's when I found that auto-plug could be really helpful but couldn't go further given this incompatibility issue. For the time being (as Google SSO is not a strict requirement for the project I am working on) I opted to use Basic Auth for now but would love to try this library in the future.

**Comment by nelsonic** [comment]
@wood-archer cool. `auth_plug` is very much in the process of being updated. Apologies it's taking so long ... ⏳ 🙄 
Please ⭐ the project as motivation for me to dedicate some time to it! 😉
